// Generated by CoffeeScript 1.6.3
module.exports = function() {
  var level, maxChars, minChars, out, params, processWord, text, word, words, _i, _len;
  text = arguments[0];
  out = [];
  params = arguments[1] || [];
  level = params.level || 'soft';
  minChars = params.minChars || 4;
  maxChars = params.maxChars || 8;
  processWord = function(_word) {
    var first, i, j, last, temp;
    if (_word.length < minChars) {
      return _word;
    }
    if (_word.length > maxChars && level === 'soft') {
      return _word;
    }
    _word = _word.split('');
    first = [_word.shift()];
    last = [_word.pop()];
    i = _word.length;
    while (--i) {
      j = Math.floor(Math.random() * (i + 1));
      temp = _word[i];
      _word[i] = _word[j];
      _word[j] = temp;
    }
    _word.unshift(first);
    _word.push(last);
    return _word.join('');
  };
  words = text.split(' ');
  for (_i = 0, _len = words.length; _i < _len; _i++) {
    word = words[_i];
    out.push(processWord(word));
  }
  return out.join(' ');
};
